import type { Project, Task, SavedView, CustomFieldDef } from '../types'
import { makeTask } from '../types'
import { COLOR_ACCENT } from '../constants'
import { stripAutoGeneratedContent } from './YamlParser'

// ─── Hydrate ────────────────────────────────────────────────────────────────

export function hydrateSavedViews(raw: unknown[]): SavedView[] {
  if (!Array.isArray(raw)) return []
  return raw
    .filter((r) => r && typeof r === 'object')
    .map((r) => {
      const v = r as Record<string, unknown>
      const filter = (v.filter ?? {}) as Record<string, unknown>
      return {
        id: (v.id as string) ?? '',
        name: (v.name as string) ?? 'Untitled',
        filter: {
          text: (filter.text as string) ?? '',
          statuses: Array.isArray(filter.statuses) ? filter.statuses : [],
          priorities: Array.isArray(filter.priorities) ? filter.priorities : [],
          assignees: Array.isArray(filter.assignees) ? filter.assignees : [],
          tags: Array.isArray(filter.tags) ? filter.tags : [],
          projects: Array.isArray(filter.projects) ? filter.projects : [],
          sprints: Array.isArray(filter.sprints) ? filter.sprints : [],
          dueDateFilter: (filter.dueDateFilter as string as SavedView['filter']['dueDateFilter']) ?? 'any',
          showArchived: (filter.showArchived as boolean) ?? false
        },
        sortKey: (v.sortKey as string) ?? 'status',
        sortDir: (v.sortDir as 'asc' | 'desc') ?? 'asc'
      }
    })
}

/** Map raw frontmatter fields to a Task, with optional overrides */
export function mapRawToTask(r: Record<string, unknown>, overrides?: Partial<Task>): Task {
  return makeTask({
    id: r.id != null ? String(r.id) : '',
    title: (r.title as string) ?? 'Untitled',
    description: (r.description as string) ?? '',
    type: (r.type as string) === 'milestone' ? 'milestone' : (r.type as string) === 'subtask' ? 'subtask' : 'task',
    projectId: (r.projectId as string) ?? '',
    projectTitle: (r.projectTitle as string) ?? undefined,
    status: (r.status as Task['status']) ?? 'todo',
    priority: (r.priority as Task['priority']) ?? 'medium',
    start: (r.start as string) ?? '',
    due: (r.due as string) ?? '',
    progress: typeof r.progress === 'number' ? r.progress : 0,
    assignees: Array.isArray(r.assignees) ? r.assignees : [],
    tags: Array.isArray(r.tags) ? r.tags : [],
    sprints: Array.isArray(r.sprints) ? r.sprints : [],
    milestoneIds: Array.isArray(r.milestoneIds) ? r.milestoneIds : [],
    subtasks: [],
    dependencies: Array.isArray(r.dependencies) ? r.dependencies : [],
    recurrence: r.recurrence && typeof r.recurrence === 'object' ? (r.recurrence as Task['recurrence']) : undefined,
    timeEstimate: typeof r.timeEstimate === 'number' ? r.timeEstimate : undefined,
    timeLogs: Array.isArray(r.timeLogs) ? (r.timeLogs as { date: string; hours: number; note: string }[]) : undefined,
    customFields:
      typeof r.customFields === 'object' && r.customFields !== null ? (r.customFields as Record<string, unknown>) : {},
    collapsed: r.collapsed === true,
    createdAt: (r.createdAt as string) ?? new Date().toISOString(),
    updatedAt: (r.updatedAt as string) ?? new Date().toISOString(),
    ...overrides
  })
}

export function hydrateTasks(raw: unknown[]): Task[] {
  if (!Array.isArray(raw)) return []
  return raw.map((r) => {
    const rec = r as Record<string, unknown>
    return mapRawToTask(rec, {
      subtasks: Array.isArray(rec.subtasks) ? hydrateTasks(rec.subtasks as unknown[]) : []
    })
  })
}

/** Hydrate a task from its frontmatter + body (individual .md file) */
export function hydrateTaskFromFile(
  frontmatter: Record<string, unknown>,
  body: string,
  filePath: string
): { task: Task; subtaskIds: string[]; parentId: string | null } {
  const task = mapRawToTask(frontmatter, {
    description: stripAutoGeneratedContent(body),
    filePath
  })
  const subtaskIds = Array.isArray(frontmatter.subtaskIds) ? (frontmatter.subtaskIds as string[]) : []
  const parentId = typeof frontmatter.parentId === 'string' && frontmatter.parentId ? frontmatter.parentId : null
  return { task, subtaskIds, parentId }
}

/** Build a Project object from frontmatter + body (without tasks) */
export function hydrateProjectFromFrontmatter(
  frontmatter: Record<string, unknown>,
  body: string,
  filePath: string,
  basename: string
): Project {
  return {
    id: (frontmatter.id as string) ?? basename,
    title: (frontmatter.title as string) ?? basename,
    description: (frontmatter.description as string) ?? body.trim(),
    color: (frontmatter.color as string) ?? COLOR_ACCENT,
    icon: (frontmatter.icon as string) ?? '\u{1F4CB}',
    tasks: [],
    customFields: (frontmatter.customFields as CustomFieldDef[]) ?? [],
    teamMembers: (frontmatter.teamMembers as string[]) ?? [],
    createdAt: (frontmatter.createdAt as string) ?? new Date().toISOString(),
    updatedAt: (frontmatter.updatedAt as string) ?? new Date().toISOString(),
    filePath,
    virtual: false,
    savedViews: hydrateSavedViews((frontmatter.savedViews as unknown[]) ?? [])
  }
}
